const data = {
  categories: [
    {
      name: "Anaaj aur Kirana (Grains & Staples)",
      items: [
        "Sugar",
        "Gud",
        "Chawal ₹50",
        "Chawal ₹80",
        "Chawal ₹120",
        "Poha",
        "Besan",
        "Mong Hari",
        "Kali Mong",
        "Dhua Dal",
        "Masoor",
        "Tuar",
        "Udaad Ki Dal",
        "Suji",
        "Maida",
        "Sakkar Bura",
        "Mishri",
        "Maggie",
        "Barri",
        "Meethi Dana",
        "Meetha Soda",
        "Tomato Ketchup",
        "Hing",
        "RK Blade",
        "Gillette Blade",
      ],
    },
    {
      name: "Tel aur Ghee (Oils & Ghee)",
      items: [
        "Sarso Awala",
        "Sarso",
        "Shanti Awala",
        "Dabar Awala",
        "Khopada Oil",
        "Bajaj Almonds",
        "Haircare",
        "Chameli",
        "Navratan",
        "Meetha Oil",
        "Kanji Oil",
        "Mumfali",
        "Tail Pouch 500g",
        "Tail Pouch 800g",
        "Tail Pouch 900g",
        "Kane 2 Litre",
        "Kane 5 Litre",
        "Kane 15 Litre",
        "Full Wajan Mai",
        "Peepa",
        "Ghee 250g",
        "Ghee 500g",
        "Ghee 1kg",
      ],
    },
    {
      name: "Snacks aur Namkeen",
      items: [
        "Chips Green and Red",
        "Rings",
        "Pop Corn",
        "Jeera Papad",
        "Light Wala",
        "Cup",
        "Sauce Wala",
        "Papa Ki Pari",
        "Tedhe Medhe",
        "Makka Mixture",
        "Bubbles",
        "Salman Khan",
        "Orange Corn",
        "Doremon",
        "Refil",
        "Sev Samosa",
        "Akash - Sev",
        "Akash - Hing Chana",
        "Akash - Aloo Bhujiya",
        "Akash - Farayali",
        "Akash - Tasty",
        "Akash - Khatta Meetha",
        "Akash - Moong Dal",
        "Akash - Potato Bite",
        "Akash - Noodles",
        "Akash - Tikha Mixture",
        "Akash - Tasty Peanuts",
        "Akash - Sev Parmal",
        "Akash - Matar",
        "Shayamji Sev",
        "Girraj ji sev",
        "Bajrang sev",
        "Sev Medium",
        "Mota",
        "Bhujiya",
        "Gathiya",
        "Farari Dal Chuda",
        "Meetha",
        "Chirpo",
        "Tale Mumfali Ke Dane",
        "Matar",
        "Allo Ki Chips",
        "Boondi",
        "Mixture",
        "Akash Sev 400gram",
        "Sev ₹30",
        "Papad ₹10",
        "Papad ₹20",
        "Cutting Papad",
        "Punga",
        "Cutting Pounga",
      ],
    },
    {
      name: "Biscuit aur Cookies",
      items: [
        "Patanjali",
        "Parle-G",
        "20-20",
        "Subisco - Cream",
        "CNC",
        "Magix",
        "Sunfest Bounce",
        "Moncoo",
        "Tosh Latkan",
        "Prabhat ₹10",
        "Prabhat ₹20",
        "Special",
        "₹50",
      ],
    },
    {
      name: "Chocolates aur Candies",
      items: [
        "Eclairs",
        "Kacha Mango",
        "Eclairs Duplicate",
        "Khopda",
        "Pulse",
        "Jelly",
        "Coco",
        "Hazmola",
        "Laddo",
        "Loli Pop",
        "Center Fresh",
        "Center Fruit",
        "Dairy Milk",
        "Five Star",
        "Snickers",
        "Kit Kat",
        "Mobile Wali",
        "Dairy Milk ₹2",
        "Imli",
        "Sonpapdi",
        "Barfi",
        "Dudh Wali",
        "Santra",
        "Gajak",
        "Ballon",
      ],
    },
    {
      name: "Masale (Spices)",
      items: [
        "Mirchi ₹10",
        "Mirchi ₹25",
        "Mirchi ₹50",
        "Mirchi (Adhi Kilo)",
        "Kashmiri Mirchi",
        "Lal Mirchi Khadi",
        "Haldi ₹10",
        "Haldi ₹25",
        "Haldi ₹50",
        "Haldi (Adhi Kilo)",
        "Dhaniya ₹10",
        "Dhaniya ₹20",
        "Dhaniya ₹50",
        "Dhaniya (Adhi Kilo)",
        "Namak",
        "Saunda Namak",
        "Khada Namak",
        "Kala Namak Khada",
        "Pushp Masala",
        "Neelam Masala ₹20",
        "Neelam Masala ₹50",
        "Khada Masala (₹10-₹20)",
        "Khula Masala",
        "Kali Mirchi",
        "Jeera",
        "Ajwain",
        "Saunf",
        "Tilli",
        "Kamal Gatta",
        "Mulathi",
        "Peepar",
        "Peepramur",
        "Raita Masla",
        "Kasturi Meethi",
        "Chana Masla",
        "Pasta Masla",
        "Maggie Masla",
        "Paneer Masla",
        "Achar Masle",
      ],
    },
    {
      name: "Pooja Samagri",
      items: [
        "Agarbatti ₹5",
        "Agarbatti ₹10",
        "Kashi Agarbatti",
        "Machhar Agarbatti",
        "Agarbatti ₹20",
        "Agarbatti ₹50",
        "Dhoop Batti",
        "Panchmeva",
        "Nariyal",
        "Loban",
        "Sindoor",
        "Pan",
        "Vatesha",
        "Elaichi",
        "Atar Ki Shishi",
        "Roli",
        "Bhoder",
        "Chironji",
        "Hawan Samgri",
        "Chana",
        "Lal Safed Kapda",
        "Aathi",
        "Pooja Badam",
        "Gol Supadi",
        "Long",
        "Mata Ki Pudiya",
        "Kapoor",
        "Kesar",
        "Makhane",
        "Parmal",
        "Joo",
        "Khopda",
        "Khopda Bura",
        "Gola",
        "Sahudana",
        "Mordana",
        "Rajgira",
        "Singhada",
        "Rui",
        "Lal Safed Dhajare",
        "Janeu",
        "Peela Dhajare",
        "Hara Dhajare",
        "Kaccha Sut",
        "Panchrango Dhaga",
      ],
    },
    {
      name: "Personal Care",
      items: [
        "Lux ₹10",
        "Lifebuoy",
        "No. 1",
        "Superia",
        "Dettol ₹10",
        "Neem ₹10",
        "Patanjali Sabun ₹10",
        "Clinic Plus",
        "Vatika Shampoo",
        "Patanjali Shampoo",
        "Dove Shampoo",
        "Head and Shoulder",
        "Dove Conditioner",
        "Chick Shampoo",
        "Patanjali Colgate ₹10",
        "Patanjali Colgate ₹20",
        "Patanjali Colgate ₹60",
        "Colgate ₹10",
        "Colgate ₹20",
        "Colgate ₹70",
        "Vicco",
        "Closeup ₹10",
        "Closeup ₹20",
        "Maxfresh ₹10",
        "Maxfresh ₹20",
        "Sukhi Colgate",
        "Brush ₹10",
        "Brush ₹20",
        "Brush ₹40",
        "Kali Dye",
        "Lal Dye",
        "Kon Mehandi ₹5",
        "Urgent Mehandi",
      ],
    },
    {
      name: "Cleaning Supplies",
      items: [
        "Bartan Sabun ₹5",
        "Bartan Sabun ₹10",
        "Kapde Sabun ₹5",
        "Kapde Sabun ₹10",
        "Sarf ₹5",
        "Sarf ₹10",
        "Sarf ₹1",
        "Sikha",
        "Mor Detergent 1 Kg",
        "Juna",
      ],
    },
    {
      name: "Tambaku aur Pan Masala (Tobacco)",
      items: [
        "Mid Land Cigarette",
        "Gold Cigarette",
        "Foursquare",
        "Steller",
        "Gold Flake",
        "Mint Cigarette",
        "American Cigarette",
        "Jarda",
        "Peeli Patti",
        "Supadi",
        "Supadi Purani",
        "Bhang Ke Antha",
        "Rajshree ₹10",
        "Rajshree ₹20",
        "Rajshree ₹40",
        "Tansen ₹20",
        "Paheli ₹10",
        "Paheli ₹20",
        "Hamraj ₹10",
        "Vimal ₹5",
        "Vimal ₹10",
        "Vimal ₹20",
        "Nakhrali",
        "Masoom",
        "Ritik Gold",
        "Nakharli Hari",
      ],
    },
    {
      name: "Stationary",
      items: [
        "Pen Blue (₹3)",
        "Pen Red (₹3)",
        "Pen Black (₹3)",
        "Pen ₹5 - Blue",
        "Pen ₹5 - Kali",
        "Pen ₹5 - Red",
        "Pen ₹10 (Chatkani)",
        "Pen ₹10 (Sada)",
        "Copy ₹10",
        "Copy ₹10 (3 Subject)",
        "Copy ₹10 (English)",
        "Copy ₹10 (Ganit)",
        "Copy ₹20",
        "Copy ₹20 (3 Subject)",
        "Copy ₹20 (English)",
        "Copy ₹20 (Ganit)",
        "Rough Register",
        "Pencil ₹5",
        "Scale",
        "Carbon",
        "Mom Color",
        "Pencil Color",
        "Sketch Color",
        "Kattar (Sharpener)",
        "Rubber (Eraser)",
        "Safed Tape",
        "Kala Tape",
        "Pinching Machine (Stapler)",
        "Fevicol",
        "Feviquick",
      ],
    },
    {
      name: "Electronics aur Hardware",
      items: [
        "LED",
        "Bulb ₹10",
        "Battery",
        "Sell Patta",
        "Dori ₹5",
        "Dori ₹10",
        "Pluge",
        "Holder ₹10",
        "Chitakni",
      ],
    },
    {
      name: "Kitchen aur Disposables",
      items: [
        "Theli 8*10",
        "Theli 9*13",
        "Theli 11*14",
        "Dudh Wali Theli",
        "Theli Adhi Kilo Ki",
        "Theli 1 Kilo Ki",
        "Theli 2 Kilo Ki",
        "Theli 3 Kilo Ki",
        "Theli 5 Kilo Ki",
        "Dauna Chota",
        "Dauna Medium",
        "Dauna Thermacol",
        "Pattal",
        "Chai Disposal",
        "Pani Disposal",
      ],
    },
    {
      name: "Dry Fruits",
      items: [
        "Kaju",
        "Kismis",
        "Munnka",
        "Badam",
        "Achar Chironji",
        "Pista",
        "Kharak",
      ],
    },
    {
      name: "Chaipatti (Tea)",
      items: [
        "Chaipatti ₹5",
        "Chaipatti ₹10",
        "Chaipatti ₹50",
        "Chaipatti 250 Gram",
        "Chaipatti 500 Gram",
        "Coffee ₹10",
      ],
    },
    {
      name: "Miscellaneous (Dusra Samaan)",
      items: [
        "Matches ₹1",
        "Matches ₹2",
        "Kharr",
        "Sui",
        "Sui Dhaga",
        "Neil",
        "Mohra",
        "Jeuda",
        "Harre",
        "Dhori Musri",
      ],
    },
    {
      name: "Medicine",
      items: [
        "Kilili Sabun",
        "Pateran Ki Shishi",
        "Peeri Panni Ki Goli ₹1",
        "Peeri Panni Ki Goli ₹5",
        "Dasth Ki Goli",
        "Vicks",
        "Band-Aid",
      ],
    },
  ],
};
export default data;
